starting worker pid=22788 on localhost:11326 at 19:51:41.997
starting worker pid=18140 on localhost:11326 at 19:51:42.016
starting worker pid=12680 on localhost:11326 at 19:51:42.031
starting worker pid=23512 on localhost:11326 at 19:51:42.044
starting worker pid=3784 on localhost:11326 at 19:51:42.057
starting worker pid=14120 on localhost:11326 at 19:51:42.068
starting worker pid=19440 on localhost:11326 at 19:51:42.084
starting worker pid=23216 on localhost:11326 at 19:51:42.096
starting worker pid=16660 on localhost:11326 at 20:14:41.514
starting worker pid=25248 on localhost:11326 at 20:14:41.517
starting worker pid=22532 on localhost:11326 at 20:14:41.544
starting worker pid=16356 on localhost:11326 at 20:14:41.550
starting worker pid=24040 on localhost:11326 at 20:14:41.560
starting worker pid=5304 on localhost:11326 at 20:14:41.584
starting worker pid=22056 on localhost:11326 at 20:14:41.596
starting worker pid=19936 on localhost:11326 at 20:14:41.608
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
starting worker pid=12992 on localhost:11326 at 20:29:06.181
starting worker pid=2104 on localhost:11326 at 20:29:06.183
starting worker pid=9020 on localhost:11326 at 20:29:06.213
starting worker pid=8836 on localhost:11326 at 20:29:06.221
starting worker pid=24424 on localhost:11326 at 20:29:06.230
starting worker pid=20120 on localhost:11326 at 20:29:06.246
starting worker pid=24700 on localhost:11326 at 20:29:06.257
starting worker pid=20752 on localhost:11326 at 20:29:06.269
starting worker pid=23896 on localhost:11326 at 20:29:10.160
starting worker pid=23424 on localhost:11326 at 20:29:10.163
starting worker pid=22764 on localhost:11326 at 20:29:10.175
starting worker pid=23196 on localhost:11326 at 20:29:10.184
starting worker pid=23964 on localhost:11326 at 20:29:10.205
starting worker pid=14416 on localhost:11326 at 20:29:10.216
starting worker pid=21468 on localhost:11326 at 20:29:10.237
starting worker pid=5272 on localhost:11326 at 20:29:10.247
starting worker pid=23096 on localhost:11326 at 20:29:12.328
starting worker pid=17192 on localhost:11326 at 20:29:12.330
starting worker pid=18664 on localhost:11326 at 20:29:12.344
starting worker pid=21672 on localhost:11326 at 20:29:12.365
starting worker pid=24116 on localhost:11326 at 20:29:12.367
starting worker pid=18120 on localhost:11326 at 20:29:12.388
starting worker pid=25224 on localhost:11326 at 20:29:12.395
starting worker pid=25364 on localhost:11326 at 20:29:12.404
starting worker pid=25424 on localhost:11326 at 20:43:38.949
starting worker pid=22344 on localhost:11326 at 20:43:38.955
starting worker pid=18304 on localhost:11326 at 20:43:38.968
starting worker pid=23488 on localhost:11326 at 20:43:38.980
starting worker pid=22392 on localhost:11326 at 20:43:39.002
starting worker pid=25304 on localhost:11326 at 20:43:39.008
starting worker pid=16480 on localhost:11326 at 20:43:39.035
starting worker pid=22808 on localhost:11326 at 20:43:39.044
starting worker pid=4024 on localhost:11326 at 20:44:03.871
starting worker pid=21608 on localhost:11326 at 20:44:03.875
starting worker pid=4064 on localhost:11326 at 20:44:03.895
starting worker pid=2448 on localhost:11326 at 20:44:03.904
starting worker pid=21564 on localhost:11326 at 20:44:03.914
starting worker pid=23796 on localhost:11326 at 20:44:03.925
starting worker pid=6888 on localhost:11326 at 20:44:03.937
starting worker pid=22104 on localhost:11326 at 20:44:03.957
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
ze(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
ze(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
starting worker pid=23152 on localhost:11326 at 20:59:47.648
starting worker pid=25108 on localhost:11326 at 20:59:47.655
starting worker pid=24908 on localhost:11326 at 20:59:47.662
starting worker pid=14416 on localhost:11326 at 20:59:47.674
starting worker pid=25400 on localhost:11326 at 20:59:47.686
starting worker pid=15080 on localhost:11326 at 20:59:47.694
starting worker pid=7480 on localhost:11326 at 20:59:47.709
starting worker pid=24580 on localhost:11326 at 20:59:47.724
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
starting worker pid=18164 on localhost:11766 at 16:58:11.548
starting worker pid=12780 on localhost:11766 at 16:58:11.556
starting worker pid=18612 on localhost:11766 at 16:58:11.566
starting worker pid=17368 on localhost:11766 at 16:58:11.583
starting worker pid=8096 on localhost:11766 at 16:58:11.592
starting worker pid=19496 on localhost:11766 at 16:58:11.613
starting worker pid=16504 on localhost:11766 at 16:58:11.622
starting worker pid=6576 on localhost:11766 at 16:58:11.633
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
